modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/romilodev/VeryRandomMod/issues" #optional

[[mods]]
modId="veryrandom"
displayName="Very Random Mod"
logoFile="logo.png" #optional
version="${version}"
updateJSONURL="https://gist.githubusercontent.com/romilodev/9796892b6e997e92affaedf092b8407c/raw" #optional
authors="Romilo903" #optional
description='''
This is a Very Random Mod!
'''

displayURL="https://github.com/romilodev/VeryRandomMod/wiki" #optional
# credits="" #optional



[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
